name: Merge Cherry-Pick to Main

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash to cherry-pick'
        required: true

jobs:
  merge_cherry_pick:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cherry-Pick Commit
      run: |
        # Cherry-pick the specified commit from the Test branch
        git cherry-pick ${{ github.event.inputs.commit_hash }}
        # Handle any conflicts and continue the cherry-pick process

    - name: Push to Main
      run: |
        # Push the cherry-picked commit to the main branch
        git push origin main
